version: '3'
services:
  php:
    build: ./php
    volumes:
      - ./htdocs:/vagrant/wwwroot
      - ./htdocs/conf.d:/etc/apache2/sites-enabled
    ports:
      - "80:80"
    depends_on:
      - mysql
      - memcached
      - elasticsearch
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
  memcached:
    image: memcached:alpine
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOSTS: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db01
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    volumes:
      - ./mysql:/var/lib/mysql
  elasticsearch:
    image: elasticsearch:1.7
    